apiVersion: v1
kind: Service
metadata:
  name: shuttle-piping
  namespace: shuttle-piping
spec:
  selector:
    app: shuttle-piping
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
